host: "localhost"
log:
  level: "info" # 日志级别
  format: "json" # 日志格式
  addSource: false # 是否在日志中包含源代码位置
  output: "stdout" # 日志输出目标
  filename: "./logs/" # 日志文件路径
  max_size: 10 # 最大文件大小 (MB)
  max_backups: 5 # 最大备份文件数
  max_age: 30 # 最大文件保留天数
  compress: true # 是否压缩备份文件
  enable_console: true # 是否启用控制台输出
  enable_file: true # 是否启用文件输出

database:
  mysql:
    host: "192.168.40.238" # 数据库主机名或 IP
    port: 3306 # 数据库端口
    username: "root" # 数据库用户名
    password: "jusha1996" # 数据库密码
    # host: "nj-cdb-aylldkq7.sql.tencentcdb.com" # 数据库主机名或 IP
    # port: 29224 # 数据库端口
    # username: "db_gantt" # 数据库用户名
    # password: "gantt1996" # 数据库密码
    dbname: "" # 数据库名称
    charset: "utf8mb4" # 字符集
    parse_time: true # 是否解析时间
    timeout: "5s" # 连接超时时间
    max_open_conns: 100 # 最大打开连接数
    max_idle_conns: 10 # 最大空闲连接数
    conn_max_lifetime: "1h" # 连接最大生存时间
    conn_max_idle_time: "5m" # 连接最大空闲时间
  redis:
    host: "192.168.40.206" # Redis 主机名或 IP
    port: 6379 # Redis 端口
    username: "" # Redis 用户名（如无可为空）
    password: "jusha1996" # Redis 密码（如无可为空）
    db: 0 # Redis 数据库索引
  obj_store:
    bucket_name: "jusha-gantt" # MinIO 存储桶名称
    minio:
      endpoint: "192.168.40.206:9000" # MinIO 服务器地址
      access_key_id: "uaxOCvsJNhvN0KUyjyC1" # MinIO 访问密钥
      secret_access_key: "jF3RdaemEXeQRQGj6lq93HNSC9lUFIDodGmYeafs" # MinIO 秘密密钥
  vector_db:
    milvus:
      address: "192.168.40.206:19530" # Milvus 服务器地址
      username: "" # Milvus 用户名 (如果需要)
      password: "" # Milvus 密码 (如果需要)
      api_key: "" # Milvus Cloud / Zilliz Cloud API Key
      use_ssl: false # 是否使用 SSL
      database: "" # Milvus 数据库名称 (默认为 default)
      connect_timeout: "5s" # 连接超时时间

discovery:
  enabled: true # 是否启用服务发现
  type: nacos # 指定类型为 nacos
  register_retries: 3 # 注册重试次数
  register_retry_interval: 10 # 注册间隔时间

  nacos:
    addresses: "192.168.40.238:8848" # Nacos 服务器地址，多个用逗号分隔
    namespaceId: "jusha-gantt" # 替换为你的 Namespace ID
    groupName: "DEFAULT_GROUP" # 服务分组
    username: "" # 如果需要认证
    password: ""
    timeoutMs: 5000
    logDir: "/tmp/nacos/log"
    cacheDir: "/tmp/nacos/cache"
    logLevel: "info"
    updateThreadNum: 2
    notLoadCache: true
    # connectTimeout: 5s # 可以单独为连接检查设置超时

license:
  url: "http://127.0.0.1:20245"
  server_name: "AGENT"

ai:
  history_number: 4
  sys_prompt:
  user_prompt:
  chat_model:
    provider: "ollama"
    name: "qwen3:32b"
    think: true
  embedding_model:
    provider: "local"
    name: "qwen3-embedding-0.6B"
  reranker_model:
    provider: "local"
    name: "qwen3-reranker-0.6B"
  ollama:
    base_url: "http://192.168.200.182:11434"
    models:
      - name: "bge-m3"
        type: "embedding"
      - name: "deepseek-r1:32b"
        type: "chat"
      - name: "qwen3:32b"
        type: "chat"
      - name: "xitao/bge-reranker-v2-m3:latest"
        type: "reranker"
      - name: "qwen3:8B"
        type: "chat"
  openai:
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    api_key: "sk-79805fdf48344f1c8327edbe967fbbdf"
    models:
      - name: "deepseek-r1-distill-llama-70b"
        type: "chat"
      - name: "deepseek-r1-distill-qwen-32b"
        type: "chat"
  local:
    base_url: "http://192.168.200.182:8200"
    models:
      - name: "qwen3-embedding-0.6B"
        type: "embedding"
      - name: "qwen3-reranker-0.6B"
        type: "reranker"

mcp:
  discovery_group_name: "mcp-server"
  client_timeout: 300 # MCP客户端超时时间（秒），默认5分钟
  health_check_timeout: 10 # 健康检查超时时间（秒）
